# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40cfefd4eb7a1f9c79c86175b1f6db408fa55c0b81cf29fb24b6c3852d939e6d7595b1e08e9e5f0169d2d79186942a49a551e82d5279e33ac63c86202a837980

test:
  secret_key_base: e1e42ab60fc60c4eaedf825473a852176fdc317233489e12b47911347d828a6760b996db06d5053a0e4064a790a8396b8a7a05b3f20b94011831ed01d9b996ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
